export const blueprints = [
  {
    id: 'classic',
    name: 'CaretTab Classic',
    desc: 'A minimalist look that matches the original design of CaretTab. Includes a search bar, digital clock and date widgets.',
    blueprint: {
      config: {
        global: {
          container: {
            background: [0, 0, 100, 0],
            borderColor: [0, 0, 100, 0],
            borderSize: 0,
            padding: 20,
            radius: 8,
            shadow: [false, 0, 0, 20, 123, 83, 40, 0.8],
          },
          element: {
            primaryColor: [210, 9, 85, 1],
            secondaryColor: [210, 9, 55, 1],
            shadow: [true, 1, 1, 2, 0, 0, 0, 1],
            tertiaryColor: [210, 29, 24, 1],
          },
          font: {
            bold: 100,
            color: [220, 15, 85, 1],
            family: 'Source Sans Pro',
            italic: false,
            letterSpacing: 0,
            override: false,
            shadow: [true, 1, 1, 2, 0, 0, 0, 1],
            size: 20,
            transform: 'none',
            underline: false,
          },
          hideSettings: false,
          wallpaper: {
            background: [145, 63, 6, 1],
            blur: 0,
            brightness: '10',
            contrast: 10,
            filter: 'normal',
            id: '',
            saturation: 10,
            scale: 100,
            size: 'cover',
            timestamp: '',
            type: 'default',
          },
          wallpaperApi: {
            authorLink: '',
            authorName: '',
            listLink: '',
            listName: '',
            photoAlt: '',
            photoLink: '',
            photoTitle: '',
          },
        },
        toolbar: {
          on: false,
        },
        layers: [
          {
            id: 'dt-cdy0gs',
            on: true,
            widget: 'date',
          },
          {
            id: 'sb-0c111m',
            on: true,
            widget: 'searchBar',
          },
          {
            id: 'dc-vfdf09',
            on: true,
            widget: 'digitalClock',
          },
        ],
        digitalClocks: [
          {
            base: {
              alignment: 'c',
              autoSize: true,
              container: {
                alignment: 'c',
                background: [0, 0, 0, 0.4],
                borderColor: [0, 0, 0, 0.8],
                borderSize: 0,
                override: false,
                padding: 20,
                radius: 8,
                shadow: [false, 1, 1, 5, 0, 0, 0, 0.8],
              },
              font: {
                bold: 400,
                color: [200, 10, 90, 1],
                family: 'Source Sans Pro',
                italic: false,
                letterSpacing: 0,
                override: false,
                shadow: [false, 1, 1, 5, 0, 0, 0, 0.8],
                size: 160,
                transform: 'none',
                underline: false,
              },
              height: 400,
              heightUnit: 'auto',
              width: 600,
              widthUnit: 'auto',
              x: 0,
              y: 0,
            },
            delimiter: {
              blink: true,
              color: [0, 0, 100, 1],
              letterSpacing: 0,
              on: true,
              override: true,
              shadow: [true, 1, 1, 5, 0, 0, 0, 0.8],
              size: 160,
              symbol1: ':',
              symbol2: ':',
              symbol3: '',
              x: 0,
              y: 14,
            },
            hour: {
              color: [0, 0, 100, 1],
              letterSpacing: 0,
              on: true,
              override: false,
              shadow: [false, 1, 1, 5, 0, 0, 0, 0.8],
              size: 120,
              twentyFour: false,
              twoDigit: false,
              x: 0,
              y: 0,
            },
            id: 'dc-vfdf09',
            label: {
              color: [0, 0, 100, 1],
              label: 'Clock',
              letterSpacing: 0,
              on: false,
              override: false,
              shadow: [false, 1, 1, 5, 0, 0, 0, 0.8],
              size: 20,
              x: 0,
              y: 0,
            },
            meridiem: {
              am: 'am',
              color: [0, 0, 100, 1],
              letterSpacing: 0,
              on: true,
              override: true,
              pm: 'pm',
              shadow: [true, 1, 1, 5, 0, 0, 0, 0.8],
              size: 60,
              x: 0,
              y: -18,
            },
            min: {
              color: [0, 0, 100, 1],
              letterSpacing: 0,
              on: true,
              override: false,
              shadow: [false, 1, 1, 5, 0, 0, 0, 0.8],
              size: 20,
              twoDigit: true,
              x: 0,
              y: 0,
            },
            monospace: true,
            relative: {
              color: [0, 0, 100, 1],
              letterSpacing: 0,
              on: false,
              override: false,
              shadow: [false, 1, 1, 5, 0, 0, 0, 0.8],
              size: 20,
              x: 0,
              y: 0,
            },
            sec: {
              color: [0, 0, 100, 1],
              letterSpacing: 0,
              on: true,
              override: false,
              shadow: [true, 1, 1, 5, 0, 0, 0, 0.8],
              size: 120,
              twoDigit: true,
              x: 0,
              y: 0,
            },
            spaceBetween: 20,
            timezone: 'local',
          },
        ],
        analogClocks: [],
        binaryClocks: [],
        dates: [
          {
            base: {
              alignment: 'c',
              autoSize: true,
              container: {
                alignment: 'c',
                background: [0, 0, 0, 0.4],
                borderColor: [0, 0, 0, 0.8],
                borderSize: 0,
                override: false,
                padding: 20,
                radius: 8,
                shadow: [false, 1, 1, 5, 0, 0, 0, 0.8],
              },
              font: {
                bold: 400,
                color: [200, 10, 90, 1],
                family: 'Source Sans Pro',
                italic: false,
                letterSpacing: 0,
                override: false,
                shadow: [false, 1, 1, 5, 0, 0, 0, 0.8],
                size: 50,
                transform: 'none',
                underline: false,
              },
              height: 400,
              heightUnit: 'auto',
              width: 600,
              widthUnit: 'auto',
              x: 0,
              y: -110,
            },
            day: {
              color: [0, 0, 100, 1],
              letterSpacing: 0,
              on: true,
              override: false,
              shadow: [false, 1, 1, 5, 0, 0, 0, 0.8],
              size: 24,
              twoDigit: false,
              x: 0,
              y: 0,
            },
            dayOfWeek: {
              abbreviated: false,
              color: [0, 0, 100, 1],
              letterSpacing: 0,
              on: true,
              override: false,
              shadow: [false, 1, 1, 5, 0, 0, 0, 0.8],
              size: 24,
              x: 0,
              y: 0,
            },
            dayOfYear: {
              color: [0, 0, 100, 1],
              letterSpacing: 0,
              on: false,
              override: false,
              prefixLabel: 'Day of year: ',
              shadow: [false, 1, 1, 5, 0, 0, 0, 0.8],
              size: 24,
              suffixLabel: '',
              threeDigit: false,
              x: 0,
              y: 0,
            },
            delimiter: {
              color: [0, 0, 100, 1],
              letterSpacing: 0,
              longSymbol1: '',
              longSymbol2: ', ',
              longSymbol3: ' ',
              longSymbol4: ', ',
              longSymbol5: '',
              on: true,
              override: false,
              shadow: [false, 1, 1, 5, 0, 0, 0, 0.8],
              shortSymbol1: '',
              shortSymbol2: ', ',
              shortSymbol3: '/',
              shortSymbol4: '/',
              shortSymbol5: '',
              size: 24,
              x: 0,
              y: 0,
            },
            format: 'middle',
            id: 'dt-cdy0gs',
            month: {
              abbreviated: false,
              color: [0, 0, 100, 1],
              letterSpacing: 0,
              on: true,
              override: false,
              shadow: [false, 1, 1, 5, 0, 0, 0, 0.8],
              size: 24,
              twoDigit: false,
              x: 0,
              y: 0,
            },
            quarter: {
              color: [0, 0, 100, 1],
              letterSpacing: 0,
              on: false,
              override: false,
              prefixLabel: 'Quarter: ',
              shadow: [false, 1, 1, 5, 0, 0, 0, 0.8],
              size: 24,
              start: '0',
              suffixLabel: '',
              x: 0,
              y: 0,
            },
            short: false,
            timezone: 'America/Los_Angeles',
            week: {
              color: [0, 0, 100, 1],
              letterSpacing: 0,
              on: false,
              override: false,
              prefixLabel: 'Week: ',
              shadow: [false, 1, 1, 5, 0, 0, 0, 0.8],
              size: 24,
              suffixLabel: '',
              twoDigit: false,
              x: 0,
              y: 0,
            },
            year: {
              color: [0, 0, 100, 1],
              letterSpacing: 0,
              on: true,
              override: false,
              shadow: [false, 1, 1, 5, 0, 0, 0, 0.8],
              size: 24,
              twoDigit: false,
              x: 0,
              y: 0,
            },
          },
        ],
        weathers: [],
        todos: [],
        notepads: [],
        quotes: [],
        quickLinks: [],
        searchBars: [
          {
            autocomplete: true,
            background: [0, 0, 100, 0],
            base: {
              alignment: 'c',
              autoSize: true,
              container: {
                alignment: 'c',
                background: [0, 0, 0, 0.4],
                borderColor: [0, 0, 0, 0.8],
                borderSize: 0,
                override: false,
                padding: 20,
                radius: 8,
                shadow: [false, 1, 1, 5, 0, 0, 0, 0.8],
              },
              font: {
                bold: 400,
                color: [200, 10, 90, 1],
                family: 'Source Sans Pro',
                italic: false,
                letterSpacing: 0,
                override: true,
                shadow: [true, 1, 1, 5, 0, 0, 0, 0.8],
                size: 22,
                transform: 'none',
                underline: false,
              },
              height: 400,
              heightUnit: 'auto',
              width: 600,
              widthUnit: 'auto',
              x: 0,
              y: 110,
            },
            borderBottom: true,
            borderColor: [0, 0, 100, 1],
            borderSize: 1,
            boxShadow: [true, 0, 1, 0, 0, 0, 0, 0.8],
            customEngine: false,
            customEngineUrl: 'https://www.google.com/search?q=%s',
            dropdown: false,
            engine: 'google',
            engineLabel: false,
            icon: true,
            id: 'sb-0c111m',
            label: 'Search the web...',
            overrideColors: true,
            padding: 6,
            radius: 0,
            size: 500,
          },
        ],
        loadsheddings: [],
        shapes: [],
        texts: [],
      },
      currentWallpaper: {},
      nextWallpaper: {},
    },
  },
  {
    id: 'taskfocused',
    name: 'Task Focused',
    desc: 'Focus on tasks with a notepad, todo list and quick links.',
    blueprint: {
      config: {
        global: {
          container: {
            background: [0, 0, 0, 0],
            borderColor: [0, 0, 0, 0.15],
            borderSize: 0,
            padding: 20,
            radius: 8,
            shadow: [false, 0, 0, 20, 0, 0, 0, 0.35],
          },
          disableSelection: false,
          element: {
            primaryColor: [220, 15, 85, 1],
            secondaryColor: [220, 15, 60, 1],
            shadow: [true, 1, 1, 2, 0, 0, 0, 1],
            tertiaryColor: [220, 15, 40, 1],
          },
          font: {
            bold: 400,
            color: [220, 15, 85, 1],
            family: 'Source Sans Pro',
            italic: false,
            letterSpacing: 0,
            shadow: [true, 1, 1, 2, 0, 0, 0, 1],
            size: 20,
            transform: 'none',
            underline: false,
          },
          hideSettings: false,
          lang: 'enUS',
          schema: '2.0',
          tabTitle: {
            custom: 'CaretTab: New tab page',
            datetime: 'ff',
            timezone: 'local',
            type: 'newtab',
          },
          wallpaper: {
            background: [220, 25, 10, 1],
            blur: 0,
            brightness: 10,
            contrast: 10,
            filter: 'normal',
            id: '',
            saturation: 10,
            scale: 100,
            size: 'cover',
            timestamp: '',
            type: 'default',
          },
          wallpaperApi: {
            authorLink: '',
            authorName: '',
            listLink: '',
            listName: '',
            photoAlt: '',
            photoLink: '',
            photoTitle: '',
          },
        },
        toolbar: {
          align: 'flex-start',
          background: [0, 0, 0, 0.4],
          borderColor: [0, 0, 0, 0.15],
          borderSize: 1,
          foreground: [0, 0, 90, 1],
          on: false,
          shadow: [true, 0, 0, 20, 0, 0, 0, 0.35],
          size: 64,
          tools: [
            {
              id: 'calculator',
              on: true,
            },
            {
              apiKey: '',
              id: 'aiChat',
              model: 'gpt-3.5-turbo',
              on: true,
            },
            {
              id: 'passwordGenerator',
              on: true,
            },
          ],
        },
        layers: [
          {
            id: 'dc-ma9nq7',
            widget: 'digitalClock',
            on: true,
          },
          {
            id: 'ql-kl6h9o',
            on: true,
            widget: 'quickLinks',
          },
          {
            id: 'td-xfjaei',
            on: true,
            widget: 'todo',
          },
          {
            id: 'np-1uv41m',
            on: true,
            widget: 'notepad',
          },
        ],
        digitalClocks: [
          {
            id: 'dc-ma9nq7',
            timezone: 'America/Los_Angeles',
            monospace: true,
            spaceBetween: 0,
            label: {
              label: 'Clock',
              on: false,
              override: false,
              color: [0, 0, 100, 1],
              shadow: [false, 1, 1, 5, 0, 0, 0, 0.8],
              size: 20,
              letterSpacing: 0,
              x: 0,
              y: 0,
            },
            hour: {
              on: true,
              twoDigit: false,
              twentyFour: false,
              override: false,
              color: [0, 0, 100, 1],
              shadow: [false, 1, 1, 5, 0, 0, 0, 0.8],
              size: 20,
              letterSpacing: 0,
              x: 0,
              y: 0,
            },
            min: {
              on: true,
              twoDigit: true,
              override: false,
              color: [0, 0, 100, 1],
              shadow: [false, 1, 1, 5, 0, 0, 0, 0.8],
              size: 20,
              letterSpacing: 0,
              x: 0,
              y: 0,
            },
            sec: {
              on: false,
              twoDigit: true,
              override: false,
              color: [0, 0, 100, 1],
              shadow: [false, 1, 1, 5, 0, 0, 0, 0.8],
              size: 20,
              letterSpacing: 0,
              x: 0,
              y: 0,
            },
            meridiem: {
              on: false,
              am: 'am',
              pm: 'pm',
              override: false,
              color: [0, 0, 100, 1],
              shadow: [false, 1, 1, 5, 0, 0, 0, 0.8],
              size: 20,
              letterSpacing: 0,
              x: 0,
              y: 0,
            },
            delimiter: {
              on: true,
              symbol1: ' ',
              symbol2: ' ',
              symbol3: '',
              blink: false,
              override: false,
              color: [0, 0, 100, 1],
              shadow: [false, 1, 1, 5, 0, 0, 0, 0.8],
              size: 20,
              letterSpacing: 0,
              x: 0,
              y: 0,
            },
            relative: {
              on: false,
              override: false,
              color: [0, 0, 100, 1],
              shadow: [false, 1, 1, 5, 0, 0, 0, 0.8],
              size: 20,
              letterSpacing: 0,
              x: 0,
              y: 0,
            },
            base: {
              width: 600,
              height: 400,
              widthUnit: 'auto',
              heightUnit: 'auto',
              autoSize: true,
              alignment: 'c',
              x: 0,
              y: 0,
              font: {
                override: false,
                color: [200, 10, 90, 1],
                family: 'Source Sans Pro',
                size: 200,
                bold: 400,
                italic: false,
                underline: false,
                letterSpacing: 0,
                shadow: [false, 1, 1, 5, 0, 0, 0, 0.8],
                transform: 'none',
              },
              container: {
                alignment: 'c',
                override: false,
                radius: 8,
                borderSize: 0,
                borderColor: [0, 0, 0, 0.8],
                background: [0, 0, 0, 0.4],
                shadow: [false, 1, 1, 5, 0, 0, 0, 0.8],
                padding: 20,
              },
            },
          },
        ],
        analogClocks: [],
        binaryClocks: [],
        dates: [],
        weathers: [],
        todos: [
          {
            base: {
              alignment: 'nw',
              autoSize: true,
              container: {
                alignment: 'nw',
                background: [0, 0, 0, 0.4],
                borderColor: [0, 0, 0, 0.8],
                borderSize: 0,
                override: false,
                padding: 20,
                radius: 8,
                shadow: [false, 1, 1, 5, 0, 0, 0, 0.8],
              },
              font: {
                bold: 400,
                color: [200, 10, 90, 1],
                family: 'Source Sans Pro',
                italic: false,
                letterSpacing: 0,
                override: false,
                shadow: [false, 1, 1, 5, 0, 0, 0, 0.8],
                size: 20,
                transform: 'none',
                underline: false,
              },
              height: 400,
              heightUnit: 'pixels',
              width: 400,
              widthUnit: 'pixels',
              x: 20,
              y: -20,
            },
            done: {
              color: [0, 0, 100, 1],
              overrideColor: false,
              strikethrough: true,
            },
            filter: 'all',
            id: 'td-xfjaei',
            label: {
              label: 'Todo',
              on: true,
            },
            list: [
              {
                done: true,
                flag: false,
                id: 'one',
                name: 'Leave a review for CaretTab',
              },
              {
                done: false,
                flag: true,
                id: 'two',
                name: 'Signup for CaretTab Premium',
              },
              {
                done: false,
                flag: false,
                id: 'three',
                name: 'Fill out this todo list',
              },
            ],
          },
        ],
        notepads: [
          {
            background: [0, 0, 0, 0.4],
            base: {
              alignment: 'sw',
              autoSize: true,
              container: {
                alignment: 'sw',
                background: [0, 0, 0, 0.4],
                borderColor: [0, 0, 0, 0.8],
                borderSize: 0,
                override: false,
                padding: 20,
                radius: 8,
                shadow: [false, 1, 1, 5, 0, 0, 0, 0.8],
              },
              font: {
                bold: 400,
                color: [0, 0, 80, 1],
                family: 'Roboto Mono',
                italic: false,
                letterSpacing: 0,
                override: true,
                shadow: [false, 1, 1, 5, 0, 0, 0, 0.8],
                size: 20,
                transform: 'none',
                underline: false,
              },
              height: 94,
              heightUnit: 'auto',
              width: 400,
              widthUnit: 'auto',
              x: 20,
              y: 20,
            },
            borderColor: [0, 0, 25, 1],
            borderRadius: 5,
            borderWidth: 0,
            height: 400,
            id: 'np-1uv41m',
            overrideColors: true,
            padding: 12,
            shadow: [false, 1, 1, 5, 0, 0, 0, 0.8],
            showCharLimit: true,
            spellCheck: true,
            sync: false,
            width: 400,
          },
        ],
        quotes: [],
        quickLinks: [
          {
            base: {
              alignment: 'ne',
              autoSize: true,
              container: {
                alignment: 'nw',
                background: [0, 0, 0, 0.4],
                borderColor: [0, 0, 0, 0.8],
                borderSize: 0,
                override: false,
                padding: 20,
                radius: 8,
                shadow: [false, 1, 1, 5, 0, 0, 0, 0.8],
              },
              font: {
                bold: 400,
                color: [200, 10, 90, 1],
                family: 'Source Sans Pro',
                italic: false,
                letterSpacing: 0,
                override: false,
                shadow: [false, 1, 1, 5, 0, 0, 0, 0.8],
                size: 24,
                transform: 'none',
                underline: false,
              },
              height: 94,
              heightUnit: 'percent',
              width: 100,
              widthUnit: 'auto',
              x: -20,
              y: -20,
            },
            id: 'ql-kl6h9o',
            layout: 'cg',
            link: {
              background: [0, 0, 0, 0.4],
              borderColor: [0, 0, 100, 1],
              borderRadius: 4,
              borderSize: 0,
              hoverBackground: [0, 0, 10, 0.1],
              iconSize: 32,
              icons: true,
              margin: 10,
              maxWidth: 250,
              openInNewTab: false,
              padding: 10,
              shadow: [false, 1, 1, 5, 0, 0, 0, 0.8],
              titles: true,
            },
            quickLinks: [
              {
                id: 'carettab',
                special: 'none',
                title: 'CaretTab',
                url: 'https://www.carettab.com',
              },
              {
                id: '7yuf8j',
                special: 'none',
                title: 'BlueCaret',
                url: 'https://www.bluecaret.com',
              },
              {
                id: 'google',
                special: 'none',
                title: 'Google',
                url: 'https://www.google.com',
              },
              {
                id: 'gmail',
                special: 'none',
                title: 'Gmail',
                url: 'https://www.gmail.com',
              },
              {
                id: '9vexw6',
                special: 'none',
                title: 'YouTube',
                url: 'https://www.youtube.com',
              },
              {
                id: 't9e2se',
                special: 'none',
                title: 'Netflix',
                url: 'https://www.netflix.com',
              },
              {
                id: 'e6ut4z',
                special: 'none',
                title: 'Hulu',
                url: 'https://www.hulu.com',
              },
              {
                id: 'ec9fjs',
                special: 'none',
                title: 'Amazon Prime',
                url: 'https://www.amazon.com/video',
              },
              {
                id: 'eeyqjh',
                special: 'none',
                title: 'Twitter',
                url: 'https://www.twitter.com',
              },
              {
                id: 'tp3bz0',
                special: 'none',
                title: 'Instagram',
                url: 'https://www.instagram.com/',
              },
              {
                id: 'kyh7qm',
                special: 'none',
                title: 'TikTok',
                url: 'https://www.tiktok.com',
              },
            ],
            type: 'ql',
          },
        ],
        searchBars: [],
        loadsheddings: [],
        shapes: [],
        texts: [],
      },
      currentWallpaper: {},
      nextWallpaper: {},
    },
  },
]
