export const blueprints = [
  {
    id: 'classic',
    name: 'CaretTab Classic',
    desc: 'A minimalist look that matches the original design of CaretTab. Includes a search bar, digital clock and date widgets.',
    blueprint: {
      config: {
        global: {
          container: {
            background: [0, 0, 0, 0],
            borderColor: [0, 0, 0, 0.15],
            borderSize: 0,
            padding: 0,
            radius: 8,
            shadow: [false, 0, 0, 20, 0, 0, 0, 0.35],
          },
          element: {
            primaryColor: [220, 15, 85, 1],
            secondaryColor: [220, 15, 60, 1],
            shadow: [true, 1, 1, 2, 0, 0, 0, 1],
            tertiaryColor: [220, 15, 40, 1],
          },
          font: {
            bold: 300,
            color: [0, 0, 100, 1],
            family: 'Source Sans 3',
            italic: false,
            letterSpacing: 0,
            shadow: [true, 1, 1, 2, 0, 0, 0, 1],
            size: 20,
            transform: 'none',
            underline: false,
          },
          wallpaper: {
            background: [220, 25, 10, 1],
            blur: 0,
            brightness: 10,
            contrast: 10,
            filter: 'normal',
            id: '',
            lock: false,
            saturation: 10,
            scale: 100,
            size: 'cover',
            timestamp: '',
            type: 'default',
          },
          wallpaperApi: {
            authorLink: '',
            authorName: '',
            listLink: '',
            listName: '',
            photoAlt: '',
            photoLink: '',
            photoTitle: '',
          },
        },
        layers: [
          {
            id: 'sb-bluprt',
            name: 'Search Bar (sb-bluprt)',
            widget: 'searchBar',
            on: true,
          },
          {
            id: 'dt-bluprt',
            name: 'Date (dt-bluprt)',
            widget: 'date',
            on: true,
          },
          {
            id: 'dc-bluprt',
            name: 'Digital Clock (dc-bluprt)',
            widget: 'digitalClock',
            on: true,
          },
        ],
        digitalClocks: [
          {
            id: 'dc-bluprt',
            timezone: 'local',
            monospace: true,
            spaceBetween: 50,
            label: {
              label: 'Clock',
              on: false,
              override: false,
              color: [0, 0, 100, 1],
              shadow: [false, 1, 1, 5, 0, 0, 0, 0.8],
              size: 20,
              letterSpacing: 0,
              x: 0,
              y: 0,
            },
            hour: {
              on: true,
              twoDigit: false,
              twentyFour: false,
              override: false,
              color: [0, 0, 100, 1],
              shadow: [false, 1, 1, 5, 0, 0, 0, 0.8],
              size: 20,
              letterSpacing: 0,
              x: 0,
              y: 0,
            },
            min: {
              on: true,
              twoDigit: true,
              override: false,
              color: [0, 0, 100, 1],
              shadow: [false, 1, 1, 5, 0, 0, 0, 0.8],
              size: 20,
              letterSpacing: 0,
              x: 0,
              y: 0,
            },
            sec: {
              on: true,
              twoDigit: true,
              override: false,
              color: [0, 0, 100, 1],
              shadow: [false, 1, 1, 5, 0, 0, 0, 0.8],
              size: 20,
              letterSpacing: 0,
              x: 0,
              y: 0,
            },
            meridiem: {
              on: true,
              am: 'am',
              pm: 'pm',
              ignoreForAlignment: false,
              override: true,
              color: [0, 0, 100, 1],
              shadow: [false, 1, 1, 5, 0, 0, 0, 0.8],
              size: 60,
              letterSpacing: 0,
              x: 0,
              y: -40,
            },
            delimiter: {
              on: true,
              symbol1: ':',
              symbol2: ':',
              symbol3: '',
              blink: false,
              override: true,
              color: [0, 0, 100, 0.4],
              shadow: [true, 1, 1, 2, 0, 0, 0, 0.8],
              size: 140,
              letterSpacing: 0,
              x: 0,
              y: 12,
            },
            relative: {
              on: false,
              override: false,
              color: [0, 0, 100, 1],
              shadow: [false, 1, 1, 5, 0, 0, 0, 0.8],
              size: 20,
              letterSpacing: 0,
              x: 0,
              y: 0,
            },
            base: {
              width: 600,
              height: 400,
              widthUnit: 'auto',
              heightUnit: 'auto',
              alignment: 'c',
              x: 0,
              y: 0,
              font: {
                override: false,
                color: [200, 10, 90, 1],
                family: 'Source Sans 3',
                size: 140,
                bold: 400,
                italic: false,
                underline: false,
                letterSpacing: 0,
                shadow: [false, 1, 1, 5, 0, 0, 0, 0.8],
                transform: 'none',
              },
              container: {
                alignment: 'c',
                override: false,
                radius: 8,
                borderSize: 0,
                borderColor: [0, 0, 0, 0.8],
                background: [0, 0, 0, 0.4],
                shadow: [false, 1, 1, 5, 0, 0, 0, 0.8],
                padding: 0,
              },
            },
          },
        ],
        dates: [
          {
            id: 'dt-bluprt',
            timezone: 'local',
            format: 'middle',
            short: false,
            delimiter: {
              on: true,
              shortSymbol1: '',
              shortSymbol2: ', ',
              shortSymbol3: '/',
              shortSymbol4: '/',
              shortSymbol5: '',
              longSymbol1: '',
              longSymbol2: ', ',
              longSymbol3: ' ',
              longSymbol4: ', ',
              longSymbol5: '',
              override: false,
              color: [0, 0, 100, 1],
              shadow: [false, 1, 1, 5, 0, 0, 0, 0.8],
              size: 24,
              letterSpacing: 0,
              x: 0,
              y: 0,
            },
            year: {
              on: true,
              twoDigit: false,
              override: false,
              color: [0, 0, 100, 1],
              shadow: [false, 1, 1, 5, 0, 0, 0, 0.8],
              size: 24,
              letterSpacing: 0,
              x: 0,
              y: 0,
            },
            month: {
              on: true,
              abbreviated: false,
              twoDigit: false,
              override: false,
              color: [0, 0, 100, 1],
              shadow: [false, 1, 1, 5, 0, 0, 0, 0.8],
              size: 24,
              letterSpacing: 0,
              x: 0,
              y: 0,
            },
            day: {
              on: true,
              twoDigit: false,
              override: false,
              color: [0, 0, 100, 1],
              shadow: [false, 1, 1, 5, 0, 0, 0, 0.8],
              size: 24,
              letterSpacing: 0,
              x: 0,
              y: 0,
            },
            dayOfWeek: {
              on: true,
              abbreviated: false,
              override: false,
              color: [0, 0, 100, 1],
              shadow: [false, 1, 1, 5, 0, 0, 0, 0.8],
              size: 24,
              letterSpacing: 0,
              x: 0,
              y: 0,
            },
            dayOfYear: {
              on: false,
              prefixLabel: 'Day of year: ',
              suffixLabel: '',
              threeDigit: false,
              override: false,
              color: [0, 0, 100, 1],
              shadow: [false, 1, 1, 5, 0, 0, 0, 0.8],
              size: 24,
              letterSpacing: 0,
              x: 0,
              y: 0,
            },
            week: {
              on: false,
              prefixLabel: 'Week: ',
              suffixLabel: '',
              twoDigit: false,
              override: false,
              color: [0, 0, 100, 1],
              shadow: [false, 1, 1, 5, 0, 0, 0, 0.8],
              size: 24,
              letterSpacing: 0,
              x: 0,
              y: 0,
            },
            quarter: {
              on: false,
              prefixLabel: 'Quarter: ',
              suffixLabel: '',
              start: '0',
              override: false,
              color: [0, 0, 100, 1],
              shadow: [false, 1, 1, 5, 0, 0, 0, 0.8],
              size: 24,
              letterSpacing: 0,
              x: 0,
              y: 0,
            },
            base: {
              width: 600,
              height: 400,
              widthUnit: 'auto',
              heightUnit: 'auto',
              alignment: 'c',
              x: 0,
              y: -110,
              font: {
                override: false,
                color: [200, 10, 90, 1],
                family: 'Source Sans 3',
                size: 50,
                bold: 400,
                italic: false,
                underline: false,
                letterSpacing: 0,
                shadow: [false, 1, 1, 5, 0, 0, 0, 0.8],
                transform: 'none',
              },
              container: {
                alignment: 'c',
                override: false,
                radius: 8,
                borderSize: 0,
                borderColor: [0, 0, 0, 0.8],
                background: [0, 0, 0, 0.4],
                shadow: [false, 1, 1, 5, 0, 0, 0, 0.8],
                padding: 0,
              },
            },
          },
        ],
        searchBars: [
          {
            id: 'sb-bluprt',
            engine: 'google',
            customEngine: false,
            customEngineUrl: 'https://www.google.com/search?q=%s',
            autocomplete: true,
            icon: true,
            engineLabel: false,
            dropdown: false,
            padding: 10,
            borderSize: 1,
            borderBottom: true,
            radius: 0,
            overrideColors: true,
            background: [0, 0, 100, 0],
            borderColor: [0, 0, 100, 0.4],
            boxShadow: [false, 0, 2, 2, 0, 0, 0, 0.2],
            label: 'Search the web...',
            base: {
              width: 565,
              height: 400,
              widthUnit: 'pixels',
              heightUnit: 'auto',
              alignment: 'c',
              x: 0,
              y: 120,
              font: {
                override: false,
                color: [200, 10, 90, 1],
                family: 'Source Sans 3',
                size: 24,
                bold: 400,
                italic: false,
                underline: false,
                letterSpacing: 0,
                shadow: [false, 1, 1, 5, 0, 0, 0, 0.8],
                transform: 'none',
              },
              container: {
                alignment: 'c',
                override: false,
                radius: 8,
                borderSize: 0,
                borderColor: [0, 0, 0, 0.8],
                background: [0, 0, 0, 0.4],
                shadow: [false, 1, 1, 5, 0, 0, 0, 0.8],
                padding: 0,
              },
            },
          },
        ],
      },
      currentWallpaper: {},
      nextWallpaper: {},
    },
  },
  {
    id: 'bookmarksbar',
    name: 'Bookmark Bar',
    desc: "The Bookmarks bar version of Quick Links, placed at the top to mimic the browser's bookmarks bar.",
    blueprint: {
      config: {
        global: {
          container: {
            background: [0, 0, 0, 0],
            borderColor: [0, 0, 0, 0.15],
            borderSize: 0,
            padding: 0,
            radius: 8,
            shadow: [false, 0, 0, 20, 0, 0, 0, 0.35],
          },
          element: {
            primaryColor: [220, 15, 85, 1],
            secondaryColor: [220, 15, 60, 1],
            shadow: [true, 1, 1, 2, 0, 0, 0, 1],
            tertiaryColor: [220, 15, 40, 1],
          },
          font: {
            bold: 400,
            color: [220, 15, 85, 1],
            family: 'Source Sans 3',
            italic: false,
            letterSpacing: 0,
            shadow: [true, 1, 1, 2, 0, 0, 0, 1],
            size: 20,
            transform: 'none',
            underline: false,
          },
          wallpaper: {
            background: [220, 25, 10, 1],
            blur: 0,
            brightness: 10,
            contrast: 10,
            filter: 'normal',
            id: '',
            lock: false,
            saturation: 10,
            scale: 100,
            size: 'cover',
            timestamp: '',
            type: 'default',
          },
          wallpaperApi: {
            authorLink: '',
            authorName: '',
            listLink: '',
            listName: '',
            photoAlt: '',
            photoLink: '',
            photoTitle: '',
          },
        },
        layers: [
          {
            id: 'ql-bluprt',
            name: 'Quick Links (ql-bluprt)',
            on: true,
            widget: 'quickLinks',
          },
        ],
        quickLinks: [
          {
            base: {
              alignment: 'n',
              container: {
                alignment: 'w',
                background: [0, 0, 0, 0.4],
                borderColor: [0, 0, 0, 0.8],
                borderSize: 0,
                override: false,
                padding: 0,
                radius: 8,
                shadow: [false, 1, 1, 5, 0, 0, 0, 0.8],
              },
              font: {
                bold: 400,
                color: [0, 0, 100, 1],
                family: 'Source Sans 3',
                italic: false,
                letterSpacing: 0,
                override: true,
                shadow: [false, 1, 1, 5, 0, 0, 0, 0.8],
                size: 16,
                transform: 'none',
                underline: false,
              },
              height: 100,
              heightUnit: 'auto',
              width: 99,
              widthUnit: 'percent',
              x: 0,
              y: -6,
            },
            id: 'ql-bluprt',
            layout: 'ch',
            link: {
              background: [0, 0, 0, 0.4],
              borderColor: [0, 0, 100, 1],
              borderRadius: 4,
              borderSize: 0,
              hoverBackground: [0, 0, 0, 1],
              iconSize: 16,
              icons: true,
              margin: 7,
              maxWidth: 130,
              openInNewTab: false,
              padding: 6,
              shadow: [false, 1, 1, 5, 0, 0, 0, 0.8],
              titles: true,
            },
            quickLinks: [],
            type: 'bk',
          },
        ],
      },
      currentWallpaper: {},
      nextWallpaper: {},
    },
  },
  {
    id: 'worldclock',
    name: 'World Clock',
    desc: 'Are you a world traveler of work with people from all over? Get multiple analog clocks for the traditional "world clock" look.',
    blueprint: {
      config: {
        global: {
          container: {
            background: [0, 0, 0, 0],
            borderColor: [0, 0, 0, 0.15],
            borderSize: 0,
            padding: 20,
            radius: 8,
            shadow: [false, 0, 0, 20, 0, 0, 0, 0.35],
          },
          element: {
            primaryColor: [145, 45, 77, 1],
            secondaryColor: [168, 55, 77, 1],
            shadow: [true, 2, 3, 4, 0, 0, 0, 1],
            tertiaryColor: [168, 55, 77, 1],
          },
          font: {
            bold: 400,
            color: [220, 15, 85, 1],
            family: 'Roboto Slab',
            italic: false,
            letterSpacing: 0,
            shadow: [true, 1, 1, 2, 0, 0, 0, 1],
            size: 20,
            transform: 'none',
            underline: false,
          },
          wallpaper: {
            background: [220, 25, 10, 1],
            blur: 0,
            brightness: '5',
            contrast: 10,
            filter: 'screen',
            id: '',
            saturation: 10,
            scale: 100,
            size: 'cover',
            timestamp: '',
            type: 'default',
          },
          wallpaperApi: {
            authorLink: '',
            authorName: '',
            listLink: '',
            listName: '',
            photoAlt: '',
            photoLink: '',
            photoTitle: '',
          },
        },
        layers: [
          { id: 'dc-bluprt', name: 'Digital Clock (dc-bluprt)', on: true, widget: 'digitalClock' },
          { id: 'ac-bluprt', name: 'Analog Clock (ac-bluprt)', on: true, widget: 'analogClock' },
          { id: 'ac-bluprt2', name: 'Analog Clock (ac-bluprt2)', on: true, widget: 'analogClock' },
          { id: 'ac-bluprt3', name: 'Analog Clock (ac-bluprt3)', on: true, widget: 'analogClock' },
          { id: 'ac-bluprt4', name: 'Analog Clock (ac-bluprt4)', on: true, widget: 'analogClock' },
          { id: 'dt-bluprt', name: 'Date (dt-bluprt)', widget: 'date', on: true },
        ],
        digitalClocks: [
          {
            base: {
              alignment: 'c',
              container: {
                alignment: 'c',
                background: [0, 0, 0, 0.4],
                borderColor: [0, 0, 0, 0.8],
                borderSize: 0,
                override: false,
                padding: 20,
                radius: 8,
                shadow: [false, 1, 1, 5, 0, 0, 0, 0.8],
              },
              font: {
                bold: 400,
                color: [168, 55, 65, 1],
                family: 'Roboto Slab',
                italic: false,
                letterSpacing: 10,
                override: true,
                shadow: [true, 1, 1, 5, 0, 0, 0, 0.8],
                size: 100,
                transform: 'none',
                underline: false,
              },
              height: 400,
              heightUnit: 'auto',
              width: 600,
              widthUnit: 'auto',
              x: 0,
              y: 220,
            },
            delimiter: {
              blink: false,
              color: [168, 76, 42, 1],
              letterSpacing: 0,
              on: true,
              override: true,
              shadow: [true, 1, 1, 5, 0, 0, 0, 0.8],
              size: 120,
              symbol1: ':',
              symbol2: ':',
              symbol3: '',
              x: -4,
              y: 20,
            },
            hour: {
              color: [0, 0, 100, 1],
              letterSpacing: 0,
              on: true,
              override: false,
              shadow: [false, 1, 1, 5, 0, 0, 0, 0.8],
              size: 20,
              twentyFour: false,
              twoDigit: true,
              x: 0,
              y: 0,
            },
            id: 'dc-bluprt',
            label: {
              color: [168, 55, 65, 1],
              label: 'LOCAL TIME',
              letterSpacing: 14,
              on: true,
              override: true,
              shadow: [true, 1, 1, 5, 0, 0, 0, 0.8],
              size: 20,
              x: 0,
              y: 30,
            },
            meridiem: {
              am: '',
              color: [168, 55, 54, 1],
              ignoreForAlignment: true,
              letterSpacing: 5,
              on: true,
              override: true,
              pm: '*',
              shadow: [false, 1, 1, 5, 0, 0, 0, 0.8],
              size: 60,
              x: 0,
              y: -12,
            },
            min: {
              color: [0, 0, 100, 1],
              letterSpacing: 0,
              on: true,
              override: false,
              shadow: [false, 1, 1, 5, 0, 0, 0, 0.8],
              size: 20,
              twoDigit: true,
              x: 0,
              y: 0,
            },
            monospace: true,
            relative: {
              color: [0, 0, 100, 1],
              letterSpacing: 0,
              on: false,
              override: false,
              shadow: [false, 1, 1, 5, 0, 0, 0, 0.8],
              size: 20,
              x: 0,
              y: 0,
            },
            sec: {
              color: [0, 0, 100, 1],
              letterSpacing: 0,
              on: false,
              override: false,
              shadow: [false, 1, 1, 5, 0, 0, 0, 0.8],
              size: 20,
              twoDigit: true,
              x: 0,
              y: 0,
            },
            spaceBetween: 0,
            timezone: 'local',
          },
        ],
        analogClocks: [
          {
            base: {
              alignment: 'c',
              container: {
                alignment: 'c',
                background: [0, 0, 0, 0.4],
                borderColor: [0, 0, 0, 0.8],
                borderSize: 0,
                override: false,
                padding: 20,
                radius: 8,
                shadow: [false, 1, 1, 5, 0, 0, 0, 0.8],
              },
              font: {
                bold: 400,
                color: [200, 10, 90, 1],
                family: 'Roboto Slab',
                italic: false,
                letterSpacing: 0,
                override: false,
                shadow: [false, 1, 1, 5, 0, 0, 0, 0.8],
                size: 30,
                transform: 'none',
                underline: false,
              },
              height: 400,
              heightUnit: 'auto',
              width: 600,
              widthUnit: 'auto',
              x: 420,
              y: -30,
            },
            center: { color: [0, 0, 100, 1], on: true },
            face: {
              borderColor: [0, 0, 100, 1],
              borderSize: 5,
              hourColor: [0, 0, 100, 1],
              minuteColor: [0, 0, 100, 1],
              override: false,
              quarterColor: [0, 0, 100, 1],
              shadow: [true, 1, 1, 5, 0, 0, 0, 0.8],
              style: 'arabicDashHour',
            },
            hand: {
              override: false,
              shadow: [false, 1, 1, 5, 0, 0, 0, 0.8],
              style: 'minimalThick',
            },
            hour: { color: [0, 0, 100, 1], on: true },
            id: 'ac-bluprt',
            label: {
              color: [168, 55, 77, 1],
              label: 'Tokyo',
              letterSpacing: 2,
              on: true,
              override: true,
              shadow: [true, 1, 1, 5, 0, 0, 0, 0.8],
              size: 30,
              x: 0,
              y: -6,
            },
            min: { color: [0, 0, 100, 1], on: true },
            relative: {
              color: [168, 45, 49, 1],
              letterSpacing: 0,
              on: true,
              override: true,
              shadow: [true, 1, 1, 5, 0, 0, 0, 0.8],
              size: 23,
              x: 0,
              y: -7,
            },
            sec: { color: [0, 0, 100, 1], on: false, smoothSeconds: false },
            size: 60,
            timezone: 'Asia/Tokyo',
          },
          {
            base: {
              alignment: 'c',
              container: {
                alignment: 'c',
                background: [0, 0, 0, 0.4],
                borderColor: [0, 0, 0, 0.8],
                borderSize: 0,
                override: false,
                padding: 20,
                radius: 8,
                shadow: [false, 1, 1, 5, 0, 0, 0, 0.8],
              },
              font: {
                bold: 400,
                color: [200, 10, 90, 1],
                family: 'Roboto Slab',
                italic: false,
                letterSpacing: 0,
                override: false,
                shadow: [false, 1, 1, 5, 0, 0, 0, 0.8],
                size: 30,
                transform: 'none',
                underline: false,
              },
              height: 400,
              heightUnit: 'auto',
              width: 600,
              widthUnit: 'auto',
              x: 140,
              y: -30,
            },
            center: { color: [0, 0, 100, 1], on: true },
            face: {
              borderColor: [0, 0, 100, 1],
              borderSize: 5,
              hourColor: [0, 0, 100, 1],
              minuteColor: [0, 0, 100, 1],
              override: false,
              quarterColor: [0, 0, 100, 1],
              shadow: [true, 1, 1, 5, 0, 0, 0, 0.8],
              style: 'arabicDashHour',
            },
            hand: {
              override: false,
              shadow: [false, 1, 1, 5, 0, 0, 0, 0.8],
              style: 'minimalThick',
            },
            hour: { color: [0, 0, 100, 1], on: true },
            id: 'ac-bluprt2',
            label: {
              color: [168, 55, 77, 1],
              label: 'Moscow',
              letterSpacing: 2,
              on: true,
              override: true,
              shadow: [true, 1, 1, 5, 0, 0, 0, 0.8],
              size: 30,
              x: 0,
              y: -6,
            },
            min: { color: [0, 0, 100, 1], on: true },
            relative: {
              color: [168, 45, 49, 1],
              letterSpacing: 0,
              on: true,
              override: true,
              shadow: [true, 1, 1, 5, 0, 0, 0, 0.8],
              size: 23,
              x: 0,
              y: -7,
            },
            sec: { color: [0, 0, 100, 1], on: false, smoothSeconds: false },
            size: 60,
            timezone: 'Europe/Moscow',
          },
          {
            base: {
              alignment: 'c',
              container: {
                alignment: 'c',
                background: [0, 0, 0, 0.4],
                borderColor: [0, 0, 0, 0.8],
                borderSize: 0,
                override: false,
                padding: 20,
                radius: 8,
                shadow: [false, 1, 1, 5, 0, 0, 0, 0.8],
              },
              font: {
                bold: 400,
                color: [200, 10, 90, 1],
                family: 'Roboto Slab',
                italic: false,
                letterSpacing: 0,
                override: false,
                shadow: [false, 1, 1, 5, 0, 0, 0, 0.8],
                size: 30,
                transform: 'none',
                underline: false,
              },
              height: 400,
              heightUnit: 'auto',
              width: 600,
              widthUnit: 'auto',
              x: -140,
              y: -30,
            },
            center: { color: [0, 0, 100, 1], on: true },
            face: {
              borderColor: [0, 0, 100, 1],
              borderSize: 5,
              hourColor: [0, 0, 100, 1],
              minuteColor: [0, 0, 100, 1],
              override: false,
              quarterColor: [0, 0, 100, 1],
              shadow: [true, 1, 1, 5, 0, 0, 0, 0.8],
              style: 'arabicDashHour',
            },
            hand: {
              override: false,
              shadow: [false, 1, 1, 5, 0, 0, 0, 0.8],
              style: 'minimalThick',
            },
            hour: { color: [0, 0, 100, 1], on: true },
            id: 'ac-bluprt3',
            label: {
              color: [168, 55, 77, 1],
              label: 'London',
              letterSpacing: 2,
              on: true,
              override: true,
              shadow: [true, 1, 1, 5, 0, 0, 0, 0.8],
              size: 30,
              x: 0,
              y: -6,
            },
            min: { color: [0, 0, 100, 1], on: true },
            relative: {
              color: [168, 45, 49, 1],
              letterSpacing: 0,
              on: true,
              override: true,
              shadow: [true, 1, 1, 5, 0, 0, 0, 0.8],
              size: 23,
              x: 0,
              y: -7,
            },
            sec: { color: [0, 0, 100, 1], on: false, smoothSeconds: false },
            size: 60,
            timezone: 'Europe/London',
          },
          {
            base: {
              alignment: 'c',
              container: {
                alignment: 'c',
                background: [0, 0, 0, 0.4],
                borderColor: [0, 0, 0, 0.8],
                borderSize: 0,
                override: false,
                padding: 20,
                radius: 8,
                shadow: [false, 1, 1, 5, 0, 0, 0, 0.8],
              },
              font: {
                bold: 400,
                color: [200, 10, 90, 1],
                family: 'Roboto Slab',
                italic: false,
                letterSpacing: 0,
                override: false,
                shadow: [false, 1, 1, 5, 0, 0, 0, 0.8],
                size: 30,
                transform: 'none',
                underline: false,
              },
              height: 400,
              heightUnit: 'auto',
              width: 600,
              widthUnit: 'auto',
              x: -420,
              y: -30,
            },
            center: { color: [0, 0, 100, 1], on: true },
            face: {
              borderColor: [0, 0, 100, 1],
              borderSize: 5,
              hourColor: [0, 0, 100, 1],
              minuteColor: [0, 0, 100, 1],
              override: false,
              quarterColor: [0, 0, 100, 1],
              shadow: [true, 1, 1, 5, 0, 0, 0, 0.8],
              style: 'arabicDashHour',
            },
            hand: {
              override: false,
              shadow: [false, 1, 1, 5, 0, 0, 0, 0.8],
              style: 'minimalThick',
            },
            hour: { color: [0, 0, 100, 1], on: true },
            id: 'ac-bluprt4',
            label: {
              color: [168, 55, 77, 1],
              label: 'New York',
              letterSpacing: 2,
              on: true,
              override: true,
              shadow: [true, 1, 1, 5, 0, 0, 0, 0.8],
              size: 30,
              x: 0,
              y: -6,
            },
            min: { color: [0, 0, 100, 1], on: true },
            relative: {
              color: [168, 45, 49, 1],
              letterSpacing: 0,
              on: true,
              override: true,
              shadow: [true, 1, 1, 5, 0, 0, 0, 0.8],
              size: 23,
              x: 0,
              y: -7,
            },
            sec: { color: [0, 0, 100, 1], on: false, smoothSeconds: false },
            size: 60,
            timezone: 'America/New_York',
          },
        ],
        dates: [
          {
            id: 'dt-bluprt',
            timezone: 'local',
            format: 'middle',
            short: false,
            delimiter: {
              on: true,
              shortSymbol1: '',
              shortSymbol2: ', ',
              shortSymbol3: '/',
              shortSymbol4: '/',
              shortSymbol5: '',
              longSymbol1: '',
              longSymbol2: ', ',
              longSymbol3: ' ',
              longSymbol4: ', ',
              longSymbol5: '',
              override: false,
              color: [0, 0, 100, 1],
              shadow: [false, 1, 1, 5, 0, 0, 0, 0.8],
              size: 24,
              letterSpacing: 0,
              x: 0,
              y: 0,
            },
            year: {
              on: true,
              twoDigit: false,
              override: false,
              color: [0, 0, 100, 1],
              shadow: [false, 1, 1, 5, 0, 0, 0, 0.8],
              size: 24,
              letterSpacing: 0,
              x: 0,
              y: 0,
            },
            month: {
              on: true,
              abbreviated: false,
              twoDigit: false,
              override: false,
              color: [0, 0, 100, 1],
              shadow: [false, 1, 1, 5, 0, 0, 0, 0.8],
              size: 24,
              letterSpacing: 0,
              x: 0,
              y: 0,
            },
            day: {
              on: true,
              twoDigit: false,
              override: false,
              color: [0, 0, 100, 1],
              shadow: [false, 1, 1, 5, 0, 0, 0, 0.8],
              size: 24,
              letterSpacing: 0,
              x: 0,
              y: 0,
            },
            dayOfWeek: {
              on: true,
              abbreviated: false,
              override: false,
              color: [0, 0, 100, 1],
              shadow: [false, 1, 1, 5, 0, 0, 0, 0.8],
              size: 24,
              letterSpacing: 0,
              x: 0,
              y: 0,
            },
            dayOfYear: {
              on: false,
              prefixLabel: 'Day of year: ',
              suffixLabel: '',
              threeDigit: false,
              override: false,
              color: [0, 0, 100, 1],
              shadow: [false, 1, 1, 5, 0, 0, 0, 0.8],
              size: 24,
              letterSpacing: 0,
              x: 0,
              y: 0,
            },
            week: {
              on: false,
              prefixLabel: 'Week: ',
              suffixLabel: '',
              twoDigit: false,
              override: false,
              color: [0, 0, 100, 1],
              shadow: [false, 1, 1, 5, 0, 0, 0, 0.8],
              size: 24,
              letterSpacing: 0,
              x: 0,
              y: 0,
            },
            quarter: {
              on: false,
              prefixLabel: 'Quarter: ',
              suffixLabel: '',
              start: '0',
              override: false,
              color: [0, 0, 100, 1],
              shadow: [false, 1, 1, 5, 0, 0, 0, 0.8],
              size: 24,
              letterSpacing: 0,
              x: 0,
              y: 0,
            },
            base: {
              width: 600,
              height: 400,
              widthUnit: 'auto',
              heightUnit: 'auto',
              alignment: 'c',
              x: 0,
              y: -250,
              font: {
                override: true,
                color: [168, 55, 77, 1],
                family: 'Roboto Slab',
                size: 40,
                bold: 400,
                italic: false,
                underline: false,
                letterSpacing: 14,
                shadow: [true, 1, 1, 5, 0, 0, 0, 0.8],
                transform: 'none',
              },
              container: {
                alignment: 'c',
                override: false,
                radius: 8,
                borderSize: 0,
                borderColor: [0, 0, 0, 0.8],
                background: [0, 0, 0, 0.4],
                shadow: [false, 1, 1, 5, 0, 0, 0, 0.8],
                padding: 20,
              },
            },
          },
        ],
      },
      currentWallpaper: {},
      nextWallpaper: {},
    },
  },
  {
    id: '90sfeverdream',
    name: "90's Fever Dream",
    desc: "Grab your neon windbreaker and Pogs, we're moonwalking our way back to the rad rollercoaster ride of the 90's!",
    blueprint: {
      config: {
        global: {
          container: {
            background: [0, 0, 0, 0],
            borderColor: [0, 0, 0, 0.15],
            borderSize: 0,
            padding: 0,
            radius: 8,
            shadow: [false, 0, 0, 20, 0, 0, 0, 0.35],
          },
          element: {
            primaryColor: [220, 15, 85, 1],
            secondaryColor: [220, 15, 60, 1],
            shadow: [true, 1, 1, 2, 0, 0, 0, 1],
            tertiaryColor: [220, 15, 40, 1],
          },
          font: {
            bold: 700,
            color: [187, 100, 38, 1],
            family: 'Chelsea Market',
            italic: false,
            letterSpacing: 0,
            shadow: [false, 1, 1, 2, 0, 0, 0, 1],
            size: 20,
            transform: 'none',
            underline: false,
          },
          wallpaper: {
            background: [253, 64, 20, 1],
            blur: 0,
            brightness: 10,
            contrast: 10,
            filter: 'normal',
            id: 'cross',
            lock: false,
            saturation: 10,
            scale: '200',
            size: 'scaleRepeat',
            timestamp: '',
            type: 'pattern',
          },
          wallpaperApi: {
            authorLink: '',
            authorName: '',
            listLink: '',
            listName: '',
            photoAlt: '',
            photoLink: '',
            photoTitle: '',
          },
        },
        layers: [
          {
            id: 'sb-bluprt',
            name: 'Search Bar (sb-bluprt)',
            on: true,
            widget: 'searchBar',
          },
          {
            id: 'ac-bluprt',
            name: 'Analog Clock (ac-bluprt)',
            on: true,
            widget: 'analogClock',
          },
          {
            id: 'wr-bluprt',
            name: 'Weather (wr-bluprt)',
            on: true,
            widget: 'weather',
          },
          {
            id: 'qt-bluprt',
            name: 'Quotes (qt-bluprt)',
            on: true,
            widget: 'quote',
          },
          {
            id: 'np-bluprt',
            name: 'Notepad (np-bluprt)',
            on: true,
            widget: 'notepad',
          },
        ],
        analogClocks: [
          {
            base: {
              alignment: 'c',
              container: {
                alignment: 'sw',
                background: [0, 0, 0, 0.4],
                borderColor: [0, 0, 0, 0.8],
                borderSize: 0,
                override: false,
                padding: 0,
                radius: 8,
                shadow: [false, 1, 1, 5, 0, 0, 0, 0.8],
              },
              font: {
                bold: 400,
                color: [200, 10, 90, 1],
                family: 'Chelsea Market',
                italic: false,
                letterSpacing: 0,
                override: false,
                shadow: [false, 1, 1, 5, 0, 0, 0, 0.8],
                size: 30,
                transform: 'none',
                underline: false,
              },
              height: 400,
              heightUnit: 'auto',
              width: 600,
              widthUnit: 'auto',
              x: 320,
              y: 170,
            },
            center: { color: [253, 64, 20, 1], on: true },
            face: {
              borderColor: [45, 100, 84, 1],
              borderSize: 0,
              hourColor: [11, 67, 61, 1],
              minuteColor: [253, 81, 79, 1],
              override: true,
              quarterColor: [48, 100, 55, 1],
              shadow: [true, 2, 2, 0, 253, 64, 37, 1],
              style: 'swiss',
            },
            hand: {
              override: true,
              shadow: [true, 2, 2, 0, 253, 64, 37, 1],
              style: 'swiss',
            },
            hour: { color: [48, 100, 55, 1], on: true },
            id: 'ac-bluprt',
            label: {
              color: [0, 0, 100, 1],
              label: 'Clock',
              letterSpacing: 0,
              on: false,
              override: false,
              shadow: [false, 1, 1, 5, 0, 0, 0, 0.8],
              size: 30,
              x: 0,
              y: -7,
            },
            min: { color: [11, 67, 61, 1], on: true },
            relative: {
              color: [0, 0, 100, 1],
              letterSpacing: 0,
              on: false,
              override: false,
              shadow: [false, 1, 1, 5, 0, 0, 0, 0.8],
              size: 30,
              x: 0,
              y: -7,
            },
            sec: {
              color: [187, 100, 38, 1],
              on: true,
              smoothSeconds: false,
            },
            size: 100,
            timezone: 'local',
          },
        ],
        weathers: [
          {
            base: {
              alignment: 'c',
              container: {
                alignment: 'c',
                background: [0, 0, 0, 0.4],
                borderColor: [0, 0, 0, 0.8],
                borderSize: 0,
                override: false,
                padding: 0,
                radius: 8,
                shadow: [false, 1, 1, 5, 0, 0, 0, 0.8],
              },
              font: {
                bold: 400,
                color: [11, 67, 61, 1],
                family: 'Chelsea Market',
                italic: false,
                letterSpacing: 0,
                override: true,
                shadow: [false, 1, 1, 5, 0, 0, 0, 0.8],
                size: 18,
                transform: 'none',
                underline: false,
              },
              height: 400,
              heightUnit: 'auto',
              width: 600,
              widthUnit: 'pixels',
              x: 130,
              y: -250,
            },
            current: {
              astro: {
                moonPhase: true,
                moonPhaseColor: [0, 0, 100, 0.5],
                sunrise: false,
                sunriseColor: [0, 0, 100, 0.5],
                sunset: false,
                sunsetColor: [0, 0, 100, 0.5],
              },
              condition: { color: [0, 0, 100, 1], on: true },
              humidity: { color: [0, 0, 100, 0.5], on: false },
              icon: {
                animated: false,
                colors: {
                  cloud: [253, 81, 79, 1],
                  moon: [45, 100, 84, 1],
                  rain: [204, 62, 61, 1],
                  snow: [204, 62, 61, 1],
                  stroke: [0, 0, 100, 0],
                  sun: [45, 100, 84, 1],
                  thunder: [48, 100, 55, 1],
                },
                on: true,
              },
              on: true,
              pressure: { color: [0, 0, 100, 0.5], on: false },
              temperature: {
                currently: true,
                currentlyColor: [50, 100, 70, 1],
                degree: true,
                feelsLike: false,
                feelsLikeColor: [50, 40, 80, 1],
              },
              wind: { color: [0, 0, 100, 0.5], on: false },
            },
            forecast: {
              day: { color: [0, 0, 100, 1], on: true },
              days: '5',
              hideToday: true,
              icon: {
                animated: false,
                colors: {
                  cloud: [253, 81, 79, 1],
                  moon: [45, 100, 84, 1],
                  rain: [204, 62, 61, 1],
                  snow: [204, 62, 61, 1],
                  stroke: [0, 0, 100, 0],
                  sun: [45, 100, 84, 1],
                  thunder: [48, 100, 55, 1],
                },
                on: true,
              },
              on: true,
              temperature: {
                degree: true,
                high: true,
                highColor: [25, 100, 70, 1],
                low: true,
                lowColor: [213, 87, 76, 1],
              },
            },
            id: 'wr-bluprt',
            label: { color: [0, 0, 100, 0.5], on: false },
            layout: '1a',
            location: {
              country: 'United States of America',
              id: 2670971,
              lat: 47.61,
              lon: -122.33,
              name: 'Seattle',
              region: 'Washington',
              url: 'seattle-washington-united-states-of-america',
            },
            overrideColors: false,
            roundDecimals: true,
            scale: true,
            twentyFour: false,
            unit: true,
            windUnit: true,
          },
        ],
        notepads: [
          {
            background: [187, 100, 38, 1],
            base: {
              alignment: 'c',
              container: {
                alignment: 'sw',
                background: [0, 0, 0, 0.4],
                borderColor: [0, 0, 0, 0.8],
                borderSize: 0,
                override: false,
                padding: 0,
                radius: 8,
                shadow: [false, 1, 1, 5, 0, 0, 0, 0.8],
              },
              font: {
                bold: 400,
                color: [253, 64, 20, 1],
                family: 'Chelsea Market',
                italic: false,
                letterSpacing: 0,
                override: true,
                shadow: [false, 1, 1, 5, 0, 0, 0, 0.8],
                size: 20,
                transform: 'none',
                underline: false,
              },
              height: 400,
              heightUnit: 'pixels',
              width: 300,
              widthUnit: 'pixels',
              x: -380,
              y: -60,
            },
            borderColor: [11, 67, 61, 1],
            borderRadius: 0,
            borderWidth: 19,
            id: 'np-bluprt',
            overrideColors: true,
            padding: 12,
            shadow: [true, 10, 10, 0, 45, 100, 84, 1],
            showCharLimit: true,
            spellCheck: true,
            sync: false,
          },
        ],
        quotes: [
          {
            base: {
              alignment: 'c',
              container: {
                alignment: 'sw',
                background: [0, 0, 0, 0.4],
                borderColor: [0, 0, 0, 0.8],
                borderSize: 0,
                override: false,
                padding: 0,
                radius: 8,
                shadow: [false, 1, 1, 5, 0, 0, 0, 0.8],
              },
              font: {
                bold: 400,
                color: [200, 10, 90, 1],
                family: 'Chelsea Market',
                italic: false,
                letterSpacing: 0,
                override: false,
                shadow: [false, 1, 1, 5, 0, 0, 0, 0.8],
                size: 30,
                transform: 'none',
                underline: false,
              },
              height: 500,
              heightUnit: 'pixels',
              width: 300,
              widthUnit: 'pixels',
              x: -40,
              y: 250,
            },
            currentQuote: 1,
            id: 'qt-bluprt',
            lastUpdate: '2023-07-09T00:00:00.000-07:00',
            quoteList: '',
            quotes: [
              {
                author: 'Alan Kay',
                id: '2o384l',
                text: 'The best way to predict the future is to invent it.',
              },
              {
                author: 'Winston Churchill',
                id: 's6484g',
                text: 'Success is not final, failure is not fatal: It is the courage to continue that counts.',
              },
              {
                author: 'Theodore Roosevelt',
                id: '64s838',
                text: "Believe you can and you're halfway there.",
              },
              {
                author: 'Thomas A. Edison',
                id: '346bd5',
                text: "I have not failed. I've just found 10,000 ways that won't work.",
              },
              {
                author: 'Albert Einstein',
                id: '46dbr8',
                text: 'In the middle of difficulty lies opportunity.',
              },
              {
                author: 'Mark Twain',
                id: '9dg001',
                text: 'The secret of getting ahead is getting started.',
              },
            ],
            random: false,
            showAuthor: true,
            showQuoteMarks: true,
          },
        ],
        searchBars: [
          {
            autocomplete: true,
            background: [11, 67, 61, 1],
            base: {
              alignment: 'c',
              container: {
                alignment: 'sw',
                background: [0, 0, 0, 0.4],
                borderColor: [0, 0, 0, 0.8],
                borderSize: 0,
                override: false,
                padding: 0,
                radius: 8,
                shadow: [false, 1, 1, 5, 0, 0, 0, 0.8],
              },
              font: {
                bold: 400,
                color: [45, 100, 84, 1],
                family: 'Chelsea Market',
                italic: false,
                letterSpacing: 0,
                override: true,
                shadow: [true, 2, 2, 0, 253, 64, 20, 1],
                size: 28,
                transform: 'none',
                underline: false,
              },
              height: 400,
              heightUnit: 'auto',
              width: 640,
              widthUnit: 'pixels',
              x: 160,
              y: -90,
            },
            borderBottom: false,
            borderColor: [253, 64, 20, 1],
            borderSize: 8,
            boxShadow: [true, 6, 6, 0, 48, 100, 55, 1],
            customEngine: false,
            customEngineUrl: 'https://www.google.com/search?q=%s',
            dropdown: false,
            engine: 'ask',
            engineLabel: true,
            icon: true,
            id: 'sb-bluprt',
            label: 'Crawl the web...',
            overrideColors: true,
            padding: 20,
            radius: 50,
          },
        ],
      },
      currentWallpaper: {},
      nextWallpaper: {},
    },
  },
]
