export const baseWidgetStyles = {
  width: 600,
  height: 400,
  autoSize: true,
  alignment: 'c',
  x: 0,
  y: 0,
  font: {
    override: false,
    color: [200, 10, 90, 1],
    family: 'Source Sans Pro',
    size: 20,
    bold: 400,
    italic: false,
    underline: false,
    letterSpacing: 0,
    shadow: [false, 1, 1, 5, 0, 0, 0, 0.8],
    transform: 'none',
  },
  container: {
    alignment: 'c',
    override: false,
    radius: 0,
    borderSize: 0,
    borderColor: [0, 0, 100, 1],
    background: [0, 0, 10, 0],
    shadow: [false, 1, 1, 5, 0, 0, 0, 0.8],
    padding: 0,
  },
}
